src/cmd/bet.rs, src/cmd/mod.rs, src/cmd/wallet.rs, src/fee_spec.rs
- a plain number now gives an absolute fee
- change "spb" to "rate"
Fixes #2
=> Improve fee description and functionality

Cargo.toml, src/bet.rs, src/bet_database.rs, src/cmd/bet.rs, src/cmd/mod.rs, src/party/bet_args.rs, src/party/offer.rs, src/party/proposal.rs, src/party/take_offer.rs
So you can remember where you put a proposal or an offer etc
=> Add the ability to add tags to bets

src/party/proposal.rs
When pasting it from twitter it gets turned into text which ruins everything!
=> Remove version emoji from proposals

src/party/offer.rs, src/party/proposal.rs
=> Fix binary event check

src/cmd/bet.rs
We were only showing it when claiming.
=> Show the txid of the claim tx

src/cmd/bet.rs, src/cmd/wallet.rs
Not need for rarely used option to be so terse.
=> Remove -p for print-tx

src/cmd/mod.rs, src/cmd/wallet.rs
Also make addresses list newest first
=> Improve tab rendering

src/party/state_machine.rs
Ok so theoretically it's possible with a re-org for this to happen.
The real reason I am doing this is because someone is stuck in cancelled
where as their bet should be confirmed!
=> Allow Cancelled => Confirmed transition

Cargo.lock, Cargo.toml
Gives descriptions for things under `/s`.
=> Upgrade olivia

.github/workflows/clippy.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, src/betting/bet.rs, src/betting/database.rs, src/betting/joint_output.rs, src/betting/offer.rs, src/betting/party/bet_args.rs, src/betting/party/mod.rs, src/betting/party/offer.rs, src/betting/party/proposal.rs, src/betting/party/state_machine.rs, src/betting/party/take_offer.rs, src/betting/proposal.rs, src/bin/gun.rs, src/change.rs, src/cmd/bet.rs, src/cmd/init.rs, src/cmd/mod.rs, src/cmd/oracle.rs, src/cmd/wallet.rs, src/config.rs, src/fee_spec.rs, src/lib.rs, tests/end_to_end.rs
The main point of this release is to switch over to using the new sync logic I built for bdk:
https://github.com/bitcoindevkit/bdk/pull/461
and to switch over to using ureq for all http requests.
=> v0.5.0 release

src/amount_ext.rs, src/betting/party/mod.rs, src/betting/party/offer.rs, src/betting/party/state_machine.rs, src/betting/party/take_offer.rs, src/cmd/bet.rs, src/fee_spec.rs
=> Fix anyhow related compilation errors, print values

src/cmd/bet.rs
Leftover betting prevention from previous PR https://github.com/LLFourn/gun/pull/65
=> Allow descriptor based wallets to bet

src/cmd/init.rs, src/config.rs
=> Support signet

src/cmd/wallet.rs
Addresses https://github.com/LLFourn/gun/issues/49
=> Add flags to list all or just internal addresses. Flag to hide addresses with zero value.

CHANGELOG.md, src/betting/bet.rs, src/betting/bet_args.rs, src/betting/offer.rs, src/betting/wallet_impls/offer.rs, src/bin/gun.rs, src/bip85.rs, src/cmd/bet.rs, src/cmd/config.rs, src/cmd/init.rs, src/cmd/mod.rs, src/cmd/wallet.rs, src/config.rs, src/database.rs, src/keychain.rs, src/signers.rs, tests/end_to_end.rs
Fixups I find while doing the docs
=> V0.6 fixups2

.github/workflows/clippy.yml
We were not running clippy on PRs
=> Enable clippy on PRs

.github/workflows/clippy.yml, .github/workflows/format.yml, .github/workflows/test.yml
because this nightly build is breaking a lot of stuff.
=> Avoid goofy nightly release for now

src/cmd/wallet.rs
Addresses https://github.com/LLFourn/gun/issues/79 
Check whether an address has been used by iterating over transactions and comparing whether any script_pubkey matches. Perhaps not the most efficient..
=> Only show unused addresses flag

Cargo.lock, Cargo.toml, src/cmd/bet.rs, src/cmd/config.rs, src/cmd/mod.rs, src/cmd/wallet.rs, src/signers.rs, src/wallet.rs
use BDK's policy tool to check whether we can spend from it before we get to the signing stage.
=> Avoid panicking when spending from watch only wallet

src/cmd/config.rs, src/cmd/init.rs
Instead you can just use gun config to add one later.
=> Remove psbt_signer_dir from init

.github/workflows/test.yml, Cargo.toml, docs/README.md, src/cmd/init.rs, src/cmd/mod.rs
was able to remove some redundant code. Also make sure not to create wallet directory unless init succeeds. Reworded some stuff too.
=> Passphrase logic fixups

src/bin/gun.rs, src/cmd/mod.rs, src/cmd/setup.rs
Setup is less technical and clearer.
=> Rename init to setup

src/bin/gun.rs, src/cmd/config.rs
Make command to get the config directory from gun.
=> Allow getting the GUN_DIR from gun

src/cmd/wallet.rs
we don't need them since you can just use cli tools to filter stuff out.
=> Remove some address options

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/README.md, src/cmd/mod.rs, src/cmd/wallet.rs
Making a release to get #102  and #53 in
=> v0.6.1 release
